---
title: "Draft Quarto document"
author:  
    - name: Nicole
      affiliations:
         - name: BBH
format: html
execute:
  echo: true
editor: 
    markdown:
        wrap: 72
        canonical: true
---

## Header 1

```{r setup}
#| include: false
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results

```{r}
tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites.")
```

```{r}
tar_read(fig_metabolite_distribution)
```

## Building the model

```{r, eval=FALSE}
log_reg_specs <- logistic_reg() %>%
  set_engine("glm")
log_reg_specs
```

```{r,eval=FALSE}
lipidomics_wide <- lipidomics %>%
  mutate(metabolite = snakecase::to_snake_case(metabolite)) %>%
  pivot_wider(names_from = metabolite, values_from = value, values_fn = mean, names_prefix = "metabolite_")
lipidomics_wide
```

```{r, eval=FALSE}
lipidomics %>%
  column_values_to_snake_case()
```

```{r, eval=FALSE}
lipidomics %>%
  column_values_to_snake_case(metabolite) %>%
  metabolites_to_wider()
```

```{r, eval=FALSE}
recipe(class ~ metabolite_lipid_ch_3_1 + age + gender,
  data = lipidomics_wide
)
```

```{r, eval=FALSE}
recipe(lipidomics_wide) %>%
  update_role(metabolite_lipid_ch_3_1, age, gender, new_role = "predictor") %>%
  update_role(class, new_role = "outcome") %>%
  step_normalize(starts_with("metabolite_"))
```

```{r, eval=FALSE}
recipe_specs <- lipidomics_wide %>%
  create_recipe_spec(metabolite_lipid_ch_3_1)
recipe_specs
```

```{r, eval=FALSE}
workflow() %>%
  add_model(log_reg_specs) %>%
  add_recipe(recipe_specs)
```

```{r, eval=FALSE}
model_workflow <- create_model_workflow(
  logistic_reg() %>%
    set_engine("glm"),
  lipidomics_wide %>%
    create_recipe_spec(metabolite_lipid_ch_3_1)
)
model_workflow
```

```{r, eval=FALSE}
fitted_model <- model_workflow %>%
  fit(lipidomics_wide)
fitted_model
```

```{r, eval=FALSE}
fitted_model %>%
  extract_fit_parsnip() %>%
  tidy(exponentiate = TRUE)
```

```{r, eval=FALSE}
fitted_model %>%
  tidy_model_output()
```

```{r, eval=FALSE}
create_model_workflow(
  logistic_reg() %>%
    set_engine("glm"),
  lipidomics_wide %>%
    create_recipe_spec(metabolite_lipid_ch_3_1)
) %>%
  fit(lipidomics_wide) %>%
  tidy_model_output()
```

## Running multiple models

```{r}
# lipidomics %>%
#     column_values_to_snake_case(metabolite) %>%
#     group_split(metabolite) %>% #one metabolite in each df
#     map(metabolites_to_wider)

# convert to a function

#' Convert the long form dataset into a list of wide form data frames.
#'
#' @param data lipidomics
#'
#' @return A list of data frames.

split_by_metaoblite <- function(data) {
  data %>%
    column_values_to_snake_case(metabolite) %>%
    dplyr::group_split(metabolite) %>% # one metabolite in each df
    purrr::map(metabolites_to_wider)
}
```

```{r}
lipidomics %>%
  split_by_metaoblite()
```

```{r}
model_estimates <- lipidomics %>%
  split_by_metaoblite() %>% # split
  map(generate_model_results) %>% # apply
  list_rbind() %>% # combine
  filter(str_detect(term, "metabolite_"))
model_estimates
```

```{r}
# lipidomics %>%
#   select(metabolite) %>%
#   mutate(term = metabolite) %>%
#   column_values_to_snake_case(term) %>%
#   mutate(term = str_c("metabolite_", term)) %>% # add "metabolite_" infront of the metabolites
#   distinct(term, metabolite) %>%
#   right_join(model_estimates, by = "term")


#' Add the original metabolite names (not as snakecase) to the model results.
#'
#' @param model_results The data frame with the model results.
#' @param data The original, unprocessed lipidomics dataset.
#'
#' @return A data frame.
#'
add_original_metabolite_names <- function(model_results, data) {
  data %>%
    dplyr::select(metabolite) %>%
    dplyr::mutate(term = metabolite) %>%
    column_values_to_snake_case(term) %>%
    dplyr::mutate(term = stringr::str_c("metabolite_", term)) %>% # add "metabolite_" infront of the metabolites
    dplyr::distinct(term, metabolite) %>%
    dplyr::right_join(model_results, by = "term")
}
```

```{r}
model_estimates %>% 
    add_original_metabolite_names(lipidomics)

```

## Figure of model estimates

```{r}
model_estimates <- tar_read(df_model_estimates)
model_estimates
```

```{r plot_estimats_function}
#| include: false
# plot_estimates <- model_estimates %>% 
#     ggplot(aes(
#         x = estimate,
#         y = metabolite,
#         xmin = estimate - std.error,
#         xmax = estimate + std.error
#     )) +
#     geom_pointrange()
# 
# plot_estimates + coord_fixed(xlim = c(0,5))
# 
# 
# 
# #' Plot the estimates and standard errors of the model results.
# #'
# #' @param results The model estimate results.
# #'
# #' @return A ggplot2 figure.
# #' 
# plot_estimates <- function(results) {
#   results %>% 
#     ggplot2::ggplot(aes(
#         x = estimate,
#         y = metabolite,
#         xmin = estimate - std.error,
#         xmax = estimate + std.error
#     )) +
#     ggplot2::geom_pointrange() +
#         ggplot2::coord_fixed(xlim = c(0,5))
# }
```

```{r}
tar_read(fig_model_estimates)
```
